require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - db/schema.rb
    - vendor/**/*
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Max: 30
Style/Documentation:
  Enabled: no
RSpec/NestedGroups:
  Max: 5
RSpec/MultipleExpectations:
  Max: 3
RSpec/ScatteredSetup:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact