steps:
  - name: gcr.io/cloud-builders/docker
    args: 
      - build
      - -t
      - gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
  - name: gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA
    dir: /app
    entrypoint: sh
    args:
      - scripts/test_report.sh
      - before-build
  - name: gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
    args: 
      - bundle
      - exec
      - rails
      - spec
    volumes:
      - name: coverage
        path: /app/coverage
  - name: gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
    entrypoint: sh
    dir: /app
    args:
      - scripts/test_report.sh
      - after-build
      - -t
      - simplecov
    env:
      - CC_TEST_REPORTER_ID=0bef4d157d44f20ce4fef62d2618e8e0b3bbc2d4c7ae9c862e1a83f461d3e64b
      - GIT_COMMIT_SHA=$COMMIT_SHA
      - GIT_BRANCH=$BRANCH_NAME
    volumes:
      - name: coverage
        path: /app/coverage
  - name: gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
    args: 
      - bundle
      - exec
      - rails
      - rubocop
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=credentials/credentials.master.json.enc
      - --plaintext-file=/kms/credentials.master.json
      - --location=global
      - --keyring=refrii-api
      - --key=production
    volumes:
      - name: kms
        path: /kms
  - name: gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
    entrypoint: sh
    args:
      - scripts/migrate.sh
      - $BRANCH_NAME
    volumes:
      - name: kms
        path: /kms
    env:
      - RAILS_ENV=production
      - RACK_ENV=production
    secretEnv:
      - MYSQL_SOCKET
      - MYSQL_DATABASE
      - MYSQL_USERNAME
      - MYSQL_PASSWORD
      - SECRET_KEY_BASE
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: sh
    args: 
      - scripts/deploy.sh
      - refrii-api
      - gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
    env:
      - RAILS_ENV=production
      - RACK_ENV=production
secrets:
  - kmsKeyName: projects/refrii-169906/locations/global/keyRings/refrii-api/cryptoKeys/production
    secretEnv:
      MYSQL_SOCKET: CiQAupArwx49ZHAtzyfRtL6txKJoQ8rWjyms9akIa7Guu8Zq6yoSYgD/p2US3sIJPSvKtrCjDI70plxsOj8jBPLpU6AqYBUQ4IjIaAgWacScGuCDD0ti4pHGnx/rWAY2VNL16E35MWOHQo3MK76ElXufjireMcwYe3NLvPwagri0U+mwjTAXGvjH
      MYSQL_DATABASE: CiQAupArw/fK9Nip+n6LvYL2SUgPPUblXj8qIUT7vIVPU3zsrrsSOwD/p2USDhiWSrZA7A8wM/ohfZ1nHVfOZZlNcdXpT38Td5Qu6ahVkQpxasoEDlSfs08kC4RzhvfpfWoC
      MYSQL_USERNAME: CiQAupArwzIrk9hzhRPEeCmcuij98kFQZLjrdzzIaba5xiDGdRcSLgD/p2USYlQbngAgGF39LYMs3voTnMTLC5fSYEqEboGbO6oS8kqNGf2zX07yJ/8=
      MYSQL_PASSWORD: CiQAupArwxhw0KP3agRoCkFMuXK55d8gsytV0A+sPgTowEs31bcSOgD/p2US/YBBjkqIEa/Sl9d0lkmOdz2nT4X7j7Fisoprm1ZvQDXGxqJ1t9kQtMZZGnjptw21Vzt6Ei0=
      SECRET_KEY_BASE: CiQAupArwxsqiomrEZgs2xtkDWukISTDtbQhMIxg7RxTttlyacISqwEA/6dlEsgU5E85nezRz8srm5QsIaqkaY9VwgzarutfKXy6huDey6K4tmGmdRoB4wY0W1TpC9vd5ncoPCEFRn+c6fGNnyBj3ldWeFDzx6MK/Onaobti7db7odnREtlc5OzM7p+py1p8vcq6paMBCGO8vjxWAVqPJD7I9zKjedT3aBhArQmNU4m34uMU8T17XdLAKXQZbyLs2tFBHDcNNtytQV7BiAVgiN3WJlY=
images:
  - gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
