steps:
  - name: gcr.io/cloud-builders/docker
    args: 
      - build
      - -t
      - gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
  - name: gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
    args: 
      - bundle
      - exec
      - rails
      - spec
  - name: gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
    args: 
      - bundle
      - exec
      - rails
      - rubocop
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=credentials.master.json.enc
      - --plaintext-file=/kms/credentials.master.json
      - --location=global
      - --keyring=refrii-api
      - --key=production
    volumes:
      - name: kms
        path: /kms
  - name: gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
    args:
      - sh
      - migrate.sh
      - $BRANCH_NAME
    volumes:
      - name: kms
        path: /kms
    env:
      - RAILS_ENV=production
      - RACK_ENV=production
    secretEnv:
      - GOOGLE_CLIENT_EMAIL
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLOUD_STORAGE_BUCKET
      - GOOGLE_PRIVATE_KEY
      - GOOGLE_PRIVATE_KEY_ID
      - GOOGLE_X509_CERT_URL
      - MYSQL_SOCKET
      - MYSQL_DATABASE
      - MYSQL_USERNAME
      - MYSQL_PASSWORD
      - FIREBASE_PROJECT_ID
      - SECRET_KEY_BASE
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: sh
    args: 
      - deploy.sh
      - refrii-api-production
      - gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
    env:
      - RAILS_ENV=production
      - RACK_ENV=production
    secretEnv:
      - GOOGLE_CLIENT_EMAIL
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLOUD_STORAGE_BUCKET
      - GOOGLE_PRIVATE_KEY
      - GOOGLE_PRIVATE_KEY_ID
      - GOOGLE_X509_CERT_URL
      - MYSQL_SOCKET
      - MYSQL_DATABASE
      - MYSQL_USERNAME
      - MYSQL_PASSWORD
      - FIREBASE_PROJECT_ID
      - SECRET_KEY_BASE
secrets:
  - kmsKeyName: projects/refrii-169906/locations/global/keyRings/refrii-api/cryptoKeys/production
    secretEnv:
      GOOGLE_CLIENT_EMAIL: CiQAupArw7Rlu9qcPIAsbBD6T8PzQvc2+8RfaDpZGfPKVxi3mLsSYQD/p2USrTP5rG6YSsx0hTMkzGQybxHH5+3buQlZVg5L25ckTOqv1IvPyxG9cKlJTI/i5ABIcRlOuWiXPH4tEZGCq9MrNv6kSZ9EPI2vrX+plEYFKvLXKWrp21T5q8lffJQ=
      GOOGLE_CLIENT_ID: CiQAupArw6IvExHQTb1eEzF7X9AzaBW+nmNuEfJm+kKg05xe1IsSPwD/p2USxVXUZsDuJxOsM3VTUHdWNs65O07F5RA+hlCwcHEWaJ1PcC8k5WkYaQA5mDf3zXFtWmwgZlptjHRYHg==
      GOOGLE_CLOUD_STORAGE_BUCKET: CiQAupArw4MGNI6TJW/jVQxaKTphx0/78fZbBMItFA/GPYHeFjQSQgD/p2USX6cO+1yq6E2WR6+7YSgYdWYWXLXWUC3UmXJ5Cy7nsUobvVyxoDh5ILcGu7WHk/NeIgUklrs2DpGeD+SQzw==
      GOOGLE_PRIVATE_KEY: CiQAupArwwwtndKPlyWZbI4/9TOLfhqyJgKLHxwNkNpv654A6qQS0g0A/6dlEn1LkBvlNlrA8FSm7kTesxMHh/fY6lT+jWcO1xQNcsq4s9rjaVpouM1tYMNvuQOufzcfBShUwoh5GU4rAsEtGw2qsSfLXyElybXiUfUVHDS2Y//apzOYrR+TG5kFiK0Rq9y5uVzviflTmkMZ1U07o4EBGBqgYNgJ7ZED1ft7rXq95Cq6XsIOif1su+1oGst61P0cXU1vO7L3Ymq4M0eQDZJ8DE/6gUo+AzBVYVkfbh0EvtRyPD1gzGPyGvf4MFGs+ZrpN6LGezBtVom5SzK0oorQyyvxabO6tLUUaoLEdYj0F+JZw/l5M9sB9T+x7n+C0EIQsNYqsZtruEfbsHw+9vJIPQlYjeAtC+GAQBp/e9QLMBUc4+QMA5eMdrnJVZ2786j46Hs5atgydOnSQHJhDjcS8Haz3S0giO7D54IVpUJ9d9jrgXAzORwFirrjtEvZkCQDK3NnnWCVmKxYDKU1gzAgiMUqWwfnZEuqfk5lnkruV9DhrI3IMWMUbZCCDzotOcxM/5bB8yhF6fpJG6vPaBRVLFN44EtczCrQXmX0Y0bjN1wBgXYViSkv6bFIiNQCzW7YQ2XfLof2uNBvwLDb1NeIFaxVMs/f0OJd3iSqpdt2LTZJUy0vuoJ08Cmslp2MQFgCOGmpkDQfm2S4Ahrs818vi8ROUU1Cnv36Xal+yUelMFeaShzsOj7joC7HauAykDtiklRQu2rwoudu19bbc+Me+g2YHgqBgEoNUouXRd98arwghNpKNtslR/Zo6IIA+F3ZQaAILtymgOpuQJwPekj3A/5uWJSIiIN8igTtGYTfS1gKhyTrOjxLVhw2Wf/ghVx6glmAi138CkpIv4roFGePF9HEheTpaY88qmPDWwldHH0q1o8PEB+WmkEyr152RWd3xbkPNeovwWYka+OsPxb6s3O81UXWRXyA68dXl4svkNQ3pe6dANkkWbwfqGQ7Mtpwy9+LWb9E3oQWuk0kuqrbQeiUiWKFoeJH/O3lmUrK1XTd7YmxYm2NkKQfvGs7fFBLr55OBq9/tbsovPK/AjH5o+CMPw1npL4jRfHJvmwmPEh2Z2sValvkBlhGNetrwEKQQGz7qi1P8POqHZBbT8FRQ76OHZjsLz9Z7Zoh0Xc93kg2Ur9sC+UEONRZjjtMUxe/OnJXK3LU05cmGIGTGRd6TTiSpuCZPhRelQ5nPG2FbXlWTk0fUyi58fzE7uxksfMRKoov6Lv75QgXAf4zDZ24FvpH63K8qe2s2FH7rCiCjp9K0uQNhbUqbHpxRXubXU7dMBaQdTa3cESBomYSmF71pGWaXUEB499oi+IgceVpH7M8EZnFPTgiahWK52h2TZuNZjscbaB0hRbbgk/WjVOXFXxQ8zcpqXHOHhGv+Uk8MiPzM7Uxn+W1CoO5uuiadYAcIOTlgIROJRVl/cFWkRL8sH8EHAMETN8Y31srHoDvh95H1PHnXmOmk+I+ChGKddL3hqlhfpwgBSXPMAgpRMLFkJaa1lC200I3muqM6mzoetiscLNM1Tnhuftb9NyRL7HU4n6H2+IJFIin/LZBWjN7yyfdk5vdEub4h3a6r2LLNspebvq7jlUjpoHjj4PX4PIUV8KgSGYBNnBSUcPol31Skvf+6WTqNAj6Zn0sWew/850SMTahDDtebMya3XiyItbR+AP2Aluf8AGvFO3uuTxA/DCISZpGosgyoUHUbVoUvcP0pu8jNA5d2z3/3GS1lfIrljSNqqFAOTc5h1XsNu7q2WTwcdPZJ5aup0mzX5O352JSmTnXY2vmH31AO6ILlsHF6Rx43dNWpmxVbKolmekUYLrUsO4rapuH4QHXTf5/VVPbd+jk68sSko5v+Xycea+jSM9INg2i2psRjilOnRvQyee7n0Q7qz+NOFGFPqZikIKMqeZx/rkFupY55gNufiLshPIlIp4W+oMNPvzXK8cUOs+KjSX2fZYGIJtrFC5xWVsxYEnm0Uv1IIzALPl/uL8AINRMeK4zvYxb7AknHRFOztEjvjx+PBzcbXIbR7Yi4h480vEXU0Yu9botWYh2UDnlwBpy8SYhBDegnE/tO81D6Tr5bdKTMbgIl7XL1Cy2CtcSKcKBLgCFJixbRUbwxIhLMbscyxnRrjvD2PRuabTXB1/zaAZiyLxfWDlgM2nWfw5N6WLcj2TLAOQi4YTrZBksPXtgvZobnGhw8eXG5FBylAg3biuXNZBaUk+SgiRi/cipDVNlfrXnnb6WTi3zlALekhTFYBtRIxf+UViR0dYgA5eEowFo9mV7qZFAxdEcolyoB6jQznIZcT++AEAs6mI9+MwQSLm7/d1sYr4=
      GOOGLE_PRIVATE_KEY_ID: CiQAupArwxewUWtaa4MOLm1mkA0ffWyCNHgKMjpXN5Al8p5ECpMSUgD/p2USy6hPlQ/m4XHnom+92F/DudkesVvvhoLZYpMBVXUARlQOfml7aebZuFA6fedBwALlYLadEYhgwqEDm70VnshXYz76WS+4VciERIB7q9A=
      GOOGLE_X509_CERT_URL: CiQAupArw7dHRoAWb7KhU+rGgXLgM26PisOGjBary6g4+5JrANoSlQEA/6dlEq5dJawIv4cM/oDKzBnreoqsgTy73Z3c0vpeb3ZlSkOx3HpZaT83TDbB9ojAt0Gjd0wgNDoplgNvVmNW+bqNfaXEf4SU6qvANtWV6qtrVTChgeswiL2yKtfEddcqkmaxUr1RF8Th0F0oj9wthEVuUefI1CgPbHc1Ez7yxwWdeX1BT5EtOu7u0x6GuiH5rGtXdw==
      MYSQL_SOCKET: CiQAupArw1bnpfLHlOwKVnS6h7YIAP0Vl3o8kxm+EWri+pJ6N/sSWAD/p2USYbChqgURanchU5XKkZ1gBDqzq4QdkTqsueZAGkYAhiU18JHrYfHldSopYzhOxoz4VOEMxOidy1KihSuRNa7vCS0Z6IbN0kqLHvV2xWeRhZ+5WJE=
      MYSQL_DATABASE: CiQAupArw/fK9Nip+n6LvYL2SUgPPUblXj8qIUT7vIVPU3zsrrsSOwD/p2USDhiWSrZA7A8wM/ohfZ1nHVfOZZlNcdXpT38Td5Qu6ahVkQpxasoEDlSfs08kC4RzhvfpfWoC
      MYSQL_USERNAME: CiQAupArwzIrk9hzhRPEeCmcuij98kFQZLjrdzzIaba5xiDGdRcSLgD/p2USYlQbngAgGF39LYMs3voTnMTLC5fSYEqEboGbO6oS8kqNGf2zX07yJ/8=
      MYSQL_PASSWORD: CiQAupArw9KfeoAJTXRga121BBh53t1TnH58xeRBUQtUMX1uAMISOgD/p2USOt1NkJfro6ZVzM/qxnGt1FZ9cUEil3EnDnsjSA2TQryz7CjxTcpxBsNJz06KLSy2ISkRJN4=
      FIREBASE_PROJECT_ID: CiQAupArw1h/ltglLewjasYvROct2z/QOT0f70qrPyMZyLId+y8SNwD/p2US0ebFTYb72c3slumtB0Keku7B2HGqxYLzPTZ+Y8l5eXhPq2kYayDme1iPyZcbweT31so=
      SECRET_KEY_BASE: CiQAupArwxsqiomrEZgs2xtkDWukISTDtbQhMIxg7RxTttlyacISqwEA/6dlEsgU5E85nezRz8srm5QsIaqkaY9VwgzarutfKXy6huDey6K4tmGmdRoB4wY0W1TpC9vd5ncoPCEFRn+c6fGNnyBj3ldWeFDzx6MK/Onaobti7db7odnREtlc5OzM7p+py1p8vcq6paMBCGO8vjxWAVqPJD7I9zKjedT3aBhArQmNU4m34uMU8T17XdLAKXQZbyLs2tFBHDcNNtytQV7BiAVgiN3WJlY=
images:
  - gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
