steps:
  - name: gcr.io/cloud-builders/docker
    args: 
      - build
      - -t
      - gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
  - name: gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
    args: 
      - bundle
      - exec
      - rails
      - spec
  - name: gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
    args: 
      - bundle
      - exec
      - rails
      - rubocop
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=credentials.staging.json.enc
      - --plaintext-file=/kms/credentials.staging.json
      - --location=global
      - --keyring=refrii-api
      - --key=$BRANCH_NAME
    volumes:
      - name: kms
        path: /kms
  - name: gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
    args:
      - sh
      - migrate.sh
      - $BRANCH_NAME
    volumes:
      - name: kms
        path: /kms
    env:
      - RAILS_ENV=production
      - RACK_ENV=production
    secretEnv:
      - GOOGLE_CLIENT_EMAIL
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLOUD_STORAGE_BUCKET
      - GOOGLE_PRIVATE_KEY
      - GOOGLE_PRIVATE_KEY_ID
      - GOOGLE_X509_CERT_URL
      - MYSQL_SOCKET
      - MYSQL_DATABASE
      - MYSQL_USERNAME
      - MYSQL_PASSWORD
      - FIREBASE_PROJECT_ID
      - SECRET_KEY_BASE
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: sh
    args: 
      - deploy.sh
      - refrii-api-staging
      - gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
    env:
      - RAILS_ENV=production
      - RACK_ENV=production
    secretEnv:
      - GOOGLE_CLIENT_EMAIL
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLOUD_STORAGE_BUCKET
      - GOOGLE_PRIVATE_KEY
      - GOOGLE_PRIVATE_KEY_ID
      - GOOGLE_X509_CERT_URL
      - MYSQL_SOCKET
      - MYSQL_DATABASE
      - MYSQL_USERNAME
      - MYSQL_PASSWORD
      - FIREBASE_PROJECT_ID
      - SECRET_KEY_BASE
secrets:
  - kmsKeyName: projects/refrii-169906/locations/global/keyRings/refrii-api/cryptoKeys/staging
    secretEnv:
      GOOGLE_CLIENT_EMAIL: CiQAeSpaetP7JQvjvsR0QSWoHtJvEcUYYOpzrFe6hRylFl6OcMcSYQCCQeAU+5v722eTr16mxYTJeeHge602INIiyT51d+YAokUNbLUZgNuAzTMX+YAAc7QdP25/9TarytEL7ovxrLhcQE4LJCa3AHhKc13puehRaNCcTCviX1QAxWQxpFzHajg=
      GOOGLE_CLIENT_ID: CiQAeSpaekzpay1y9tianZZZVvz+VtKbOziQBpbkaDJYqfuOwL4SPwCCQeAUjWEyatKyBq8bCWG9QeMSAcHhFNp8POYDXjJBCx+CsGDoGWI9hssxoLOzWBO9l+I/Z5WECQb2yByIow==
      GOOGLE_CLOUD_STORAGE_BUCKET: CiQAeSpaeq41haN+gBwEWWkm2SbkpVM0oRd2N0VcVUrPlsMVrfISPwCCQeAUYnHlQCKfh8emNzIG8rahZlfn2b3PEZmd0Q6OwPzTog1jynLKW0AB4PKNEgHm4sAomAWdiRtqO7TxEg==
      GOOGLE_PRIVATE_KEY: CiQAeSpaekNW4C4aO4zqCirUbG7Wmwu87++iXU6KLQG91RWVT+kS0g0AgkHgFFDK8+ngMPMf464e1VHCD9JYTV44ZXHI5hcTprgK5pQ3u+MygaxGWjCm7TYBCD2MtlUZvgIogHE9qQbCRCNHknmkz6c2tOuTbkb3SEua+FTvdONoG+TQ02XsoIXtC+vi4wzyEpZBXcTtUwhXRqwn2Ct/uIpJzU+CIyeuVx2YPain3pxmSGwi8HZmabZQ4Sh2GEXYyDEmOOpGHTkwG3Y/lsGGkHbCPp2L68n7tdHdAAIqo324Iy7KL6ZVxRu59jUPwYFHQecEfKKrY7m06XAVh+NS5rZxXZ3Osh3GtguVXnafXUjugUCyUe3hC3B2AoypJk6Etkzb1tkdzgIkto8vnR1OVgXFC2kph1ZEpZ+TVJ+Eb2Hf7cjQUiqMzefaw64uEJKgfwr0SxBB6ImyLkJprAzWwecZIY/JlR3BRWWtWRr82jiY9lNbPRvi6bRK44wUu26VsOT2fpFsOPqBwyxuA/WJz98DLmTdbqvdUN4PenwhCO0iwtsZVpbUbqPshNfnTE4GV7JCiLQ++MjZOtKJRPVNSfeffVZNxH+XG31fJ2iDleItwAD77Yosvr6mDAF/hnAjzZp6fKRyp8rASEzKvCFPKuSsohyi5eD1KiKUM5kYEtlC7opKYre4ZP7CFC7c5/fVeBfvSuB2u/UcDnco1uZNEG5YaBwhr5mTKxzO+Ae+c47hLvuJtRngJSJVrwvP1vjMrP2FU4FHrkVw9JtfkEdNEA71xrsTilOpo9Iguc2r1RcM7XrohfJGTyKGwheFqgwOA5ucr8mQSmv4qwZs3LOWvoKvj2oDu0qkbPLB4RXjTHc1lgaW/1FRA7iPS0V22skn/5kndbHdwz/kotB3m9x4BqVe1Jpp5tDRc31iLLutnSbL6guyXVxBXIE+nlgOGoPwzhqlV8ed/46HelAKhLBH0OCFRdxj9U9sXTyENx0SPaZO6iNWK0rFhMPTc6QOvJmEmYSzyMuM4k7dB2LnJLN/3VUL47aiZKEwUUNMt4jLJIefq554J2zRhR0V2dJkCi+aeMk5S6hKelqi/2e4FJdTtGEjaq3iU5Xx6L1lweveRRCpvm6DooTXwBOUW7pAdrSWMxukAijbg+j7MS3a3ExbzkPczcoD3dwu+Fp9dnJwW/OJ8wRhYtgyp2b6VUN06+4z8VOG3FfYUpTxQKA277B9WR2PSSago7xSzKPqyOaHFfYH0P3aXzG5IMApRXfv5Q+JLU6ngHKM4sa3leNiShLWgCPZlJPQL2jYb5oZd7JtOCmWLdoE/me4afxAmRLfaNLm+mbgbds6pEXwlPw+diaJmigEQHJXNL8aWoGVsdWWyllP1uCTHv5uGAbVYWhD35QZX0yQwE+qB+OA1Rw0DthZ7Vm2ucGzpSwX1M3v9RAyppaItqlxTZ+KfMshxSj2LeLGaAyNjE+A1Uc4beCf00MVpWp1KU3ox0lMvlZI+HdBb8lwIa/dEzouowlDEKDlT3XEjilguWLtCjS+SpVg7WOy8ycegVLhoxDcr+YKvNxefBSXOKXTt2MZaLowGpUXpgW4L6M7rbsM1kO14AI86uhjX9tAbMykhgqNFXhhY+/Gp3AZ2FjPV4o3o18BkAJr0RohHl7A4IgY8wwvopdyi2aYNqo6HoUBZrvmPHgYsOGhu28sucAZAmvBfiAt8yQ8KKFtSxgixmxl4/v/dH9X7sEO7T5bhGQYtladlWN59HXfHPZfqckgPbw1PxKzlzleBLBiOdCuEetiW8S2VW7tH3H4lOm3UrDUxqZy65QoMOPSPC3B3A7048nlH9JBGNHlHyJW97gxbdPGPU8yUzZHVfzfPeNA/erNW2PNNS9XcHAHwGiFvil7NVuDo6O+vU36DEPeraiY3jNXdAlXqhY/xozJhiwVdqy5b522RIfx0s2MaEpctyqK6Vn+EVbT7u5lksa2XoPMWiL6+9IidxpNqyB/yDcoZKqmHvP3FJAK1RN37EIQDc7RKTaePW7A+v+40AVHYAjVPkZin/eHrz+ij2d/l3AfjDLFD4d2N9bxOsxoJw2Fs6WNWyccmgEk3GMvMbSpDxM+1mT9gSqvomXKEqW1SjhNyyeuZ6PgRSmOF75A8XJrKDmAmeR6Xob9mB2EYyFbQzBnR5wdUtZy+JPocx0+m7VNROtQaxwgUP0+QsTUme2GSN1lykJcsCXiF58UTAlNWd2Ltsrx+lxawsGOG8YTrY3FFF1GxwjrvJL0GgVFMyPOFIm5+rq1AVAbcQTG34nezSAuIKMOrWluUA1flIY/0GY0gKhGnrybvhBP5N8VDvGBKc5GaYkN+877wrkZXmCx8EId8SdHqwaOJ/8=
      GOOGLE_PRIVATE_KEY_ID: CiQAeSpaejPFKnb5MMRetAzsb4k3DT5ZrtKWUlSGl4VSFfJu9UASUgCCQeAU64PGbY1Afjo+gLCQW6rN4M1m3FdwRoVnm0aglumtQuthK0Q84pahXYfNt7tKGuV3l8uMcsBbs9V0y/ntX4AupB7doMMPYZZyNCYrxII=
      GOOGLE_X509_CERT_URL: CiQAeSpaeu3Xfne1nEU8oatyetQY7eE+YKEaV60LBm7nkpI4KQYSlQEAgkHgFM1zcnAaBUurZn/qD80LsFPynGYRV4J+alUO1WKegemTKfFtywjkxKJX6nVerY3QNkQf9OFulJLjkyjY9GkvCnkicnvzOoWgvCAZ65oCK1mUVALgOKhBRAAewdNrDz3zrfl9290xfSbP/W90l/XCK+dBRwsmZ1TBi5Y+EfU3XyxG9dJrD+PdqLACVWTrW76jHw==
      MYSQL_SOCKET: CiQAeSpaeqgDAcmbndIee6Wehr0tMRNqhtppBwnxaWGVKzGhkUoSWACCQeAUHLWEW1kLj6JaCJl8A7t+AY0coeqD5XWHKAa+eLrRTrBzsvSz/86WQN2EIjuWy6g144lHvVP7NNiBTCdEvZbbmqtwaQXIklD9GTstPw9o73VMUTg=
      MYSQL_DATABASE: CiQAeSpaemhUl7vdoBsX9xlh6Nf2aBtHp/N/WumG+pGjjmp0oLcSOACCQeAUaYAknChNUAR2VjXq/lzyEam52weg7DRvK2nDhxXf+Ef0q+N6l4KC4F+jVxZLjBRps4pw
      MYSQL_USERNAME: CiQAeSpaeonbfVojGnVEig7fcpG9mKFoQPWgKwy4CUGhrHdnEqcSLgCCQeAU4YJ4F4/60VRZapaZDwgvnUSAKfAkOLZwLWvJN5LOtx1CbocCbum+4Ms=
      MYSQL_PASSWORD: CiQAeSpaeuundpa8tvDSdJ7WRYfJNievzBbceFQBqvaPskdA3CoSOgCCQeAUt7MCdISdtvziBjuHi/QuEW2bvl+34DdEC1plrWti3uUhtJQfI830Q49vTQasINnWZiPwh1U=
      FIREBASE_PROJECT_ID: CiQAeSpaeiamQoKYTHKOdIPy4OG9HzGJJpDb+JIHW+HaT6o/nJoSNwCCQeAUx/T9QiqxBp3FndFTFQf59YzbB0PQZpUUvwidGaeHRlQm8QVakxztMTepxSttYaq+P7o=
      SECRET_KEY_BASE: CiQAeSpaeuQSN0XCV/GZ1hJWrpk/wjN4317zIp12GPM/EJadfjUSqwEAgkHgFFYKdlRsNxhuByQVPUurwu6JkooXV4CGUngsbdJisBdfgwbMRm+byg1KZR6hAYIBFX9gW0MeG1vGEqtvb1gmzhUv8Jjn3ibv2+r1LhYOXEFewKFxirw4gOzVXEuZ7Kf7wM2vuCS8VcHBUSSmYdJ6zqVAybmcGyjvLnB6oDTwY3fMD0zRaDtK17F4j+i8kZTbnfstQ30bdgNiyaYYtDZdFO1AF1UkBuE=
images:
  - gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
