steps:
  - name: gcr.io/cloud-builders/docker
    args: 
      - build
      - -t
      - gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
      - --cache-from
      - gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
  - name: gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
    args: 
      - bundle
      - exec
      - rails
      - spec
  - name: gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
    args: 
      - bundle
      - exec
      - rails
      - rubocop
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=credentials/credentials.staging.json.enc
      - --plaintext-file=/kms/credentials.staging.json
      - --location=global
      - --keyring=refrii-api
      - --key=staging
    volumes:
      - name: kms
        path: /kms
  - name: gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
    entrypoint: sh
    args:
      - scripts/migrate.sh
      - $BRANCH_NAME
    volumes:
      - name: kms
        path: /kms
    env:
      - RAILS_ENV=production
      - RACK_ENV=production
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: sh
    args: 
      - scripts/deploy.sh
      - refrii-api-staging
      - gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
    env:
      - RAILS_ENV=production
      - RACK_ENV=production
images:
  - gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME
