steps:
  - name: gcr.io/cloud-builders/docker
    args: 
      - build
      - -t
      - gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA
      - .
  - name: gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA
    args: 
      - bundle
      - exec
      - rake
      - spec
  - name: gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA
    args: 
      - bundle
      - exec
      - rake
      - rubocop
images:
  - gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA
