version: "3"
services:
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./db/data.yml:/app/db/data.yml
    environment:
      - SECRET_KEY_BASE
      - RAILS_ENV=production
      - RACK_ENV=production
      - MYSQL_DATABASE=refrii
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=password
      - MYSQL_HOSTNAME=db
    restart: unless-stopped
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=refrii
      - MYSQL_ROOT_PASSWORD=password
    restart: unless-stopped
