version: "3"
services:
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      - SECRET_KEY_BASE
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_DATABASE
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USERNAME
      - POSTGRESQL_PASSWORD
    restart: unless-stopped
  postgres:
    image: postgres:9.6
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    restart: unless-stopped
