default: &default
  auth0_client_id: <%= ENV['AUTH0_CLIENT_ID'] %>
  auth0_client_secret: <%= ENV['AUTH0_CLIENT_SECRET'] %>
  auth0_domain: <%= ENV['AUTH0_DOMAIN'] %>
  firebase:
    peoject_id: <%= ENV['FIREBASE_PROJECT_ID'] %>

development:
  <<: *default
  secret_key_base: b7db7d1a0bd66c10ef268fc2cae8dce8c2cd1e035abeddc2464c83c5c5b9e7fc56061bbc20b57217120e45160ca0f46c9d5a02ab302e5dc605be004e18fc97eb

test:
  <<: *default
  secret_key_base: f98324d417886a650a08f6be9e4ebb01b1b3a1b11722bc12ce6d23ae242fa7d2e672c7a6c7d2de9cf478b6cb2298cab175f20c9fe2e1bb453a37ef68f20f0505

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
