local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
 
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
 
google:
  service: GCS
  keyfile: {
    type: "service_account",
    project_id: "<%= Rails.application.credentials.dig(:google, :project_id) %>",
    private_key_id: "<%= Rails.application.credentials.dig(:google, :private_key_id) %>",
    private_key: "<%= Rails.application.credentials.dig(:google, :private_key) %>",
    client_email: "<%= Rails.application.credentials.dig(:google, :client_email) %>",
    client_id: "<%= Rails.application.credentials.dig(:google, :client_id) %>",
    auth_uri: "https://accounts.google.com/o/oauth2/auth",
    token_uri: "https://accounts.google.com/o/oauth2/token",
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs",
    client_x509_cert_url: "<%= Rails.application.credentials.dig(:google, :client_x509_cert_url) %>"
  }
  project: <%= Rails.application.credentials.dig(:google, :project_id) %>
  bucket: <%= Rails.application.credentials.dig(:google, :bucket) %>
