local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
 
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
 
google:
  service: GCS
  keyfile: {
    type: "service_account",
    project_id: "<%= ENV['FIREBASE_PROJECT_ID'] %>",
    private_key_id: "<%= ENV['GOOGLE_PRIVATE_KEY_ID'] %>",
    private_key: "<%= ENV['GOOGLE_PRIVATE_KEY'] %>",
    client_email: "<%= ENV['GOOGLE_CLIENT_EMAIL'] %>",
    client_id: "<%= ENV['GOOGLE_CLIENT_ID'] %>",
    auth_uri: "https://accounts.google.com/o/oauth2/auth",
    token_uri: "https://accounts.google.com/o/oauth2/token",
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs",
    client_x509_cert_url: "<%= ENV['GOOGLE_X509_CERT_URL'] %>"
  }
  project: <%= ENV["FIREBASE_PROJECT_ID"] %>
  bucket: <%= ENV["GOOGLE_CLOUD_STORAGE_BUCKET"] %>